BITBUCKET_SSH_KEY = """-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEApu/pDQm4nMi80BwDnv7cd1E8k6oLkPOJ8paQoA2I2AD+jDODbuZC
jkpfZshl2g2afxiahM71BtYydZJFiuokurNlnNlEPJ2EwYRqA2PAqiqmYHrVvDbK24CbwB
gvvWSTplTL0vqokYqLkq8GUV1c1F+3Jsqco1Tt8Q6yDCOxp3tKqmeT5OnxbuHpdSsiu92c
qeJ/5M8TfhOg0iuqOGelUTeoH0M/Ma3CYcEhRNq98qff8iNFW614Y3i0BS9/ueagwBraf2
JCXUUX9L7WBNZ5Ki53hXpPUpm3EcoaXytXzw+dtL5VGkZb2BYSIZHKlt2FBrWypXUER3xp
I+yxkunjSokqNwBdFEdHtLz56idVfJg5k0aIR/nO+swbzYtTGgOpEK1nsU/ecNnxGU6n/d
KlP7Lfw4jww3N7QIQDuaqOAULZ7qaup8JUF3v5kpue4V6ncxHPyHXFbSVrufPbHz6PFMv0
yi25wq31eUDafL+xDe/NXZ2jh4Tm/7d6dbYunW9PAAAFiAtDunkLQ7p5AAAAB3NzaC1yc2
EAAAGBAKbv6Q0JuJzIvNAcA57+3HdRPJOqC5DzifKWkKANiNgA/owzg27mQo5KX2bIZdoN
mn8YmoTO9QbWMnWSRYrqJLqzZZzZRDydhMGEagNjwKoqpmB61bw2ytuAm8AYL71kk6ZUy9
L6qJGKi5KvBlFdXNRftybKnKNU7fEOsgwjsad7Sqpnk+Tp8W7h6XUrIrvdnKnif+TPE34T
oNIrqjhnpVE3qB9DPzGtwmHBIUTavfKn3/IjRVuteGN4tAUvf7nmoMAa2n9iQl1FF/S+1g
TWeSoud4V6T1KZtxHKGl8rV88PnbS+VRpGW9gWEiGRypbdhQa1sqV1BEd8aSPssZLp40qJ
KjcAXRRHR7S8+eonVXyYOZNGiEf5zvrMG82LUxoDqRCtZ7FP3nDZ8RlOp/3SpT+y38OI8M
Nze0CEA7mqjgFC2e6mrqfCVBd7+ZKbnuFep3MRz8h1xW0la7nz2x8+jxTL9MotucKt9XlA
2ny/sQ3vzV2do4eE5v+3enW2Lp1vTwAAAAMBAAEAAAGAC1z3QyDvRRTQ7WWKxY7ZmPGZqv
9/LA23zSB8lbh2ISXoLcjv4GOiEidz2P45GJ+mbZJSKkogGagI5UHgo/UOLPs7JnMPlwSt
3bJSuQpYOf0PODAETnx4UHqvn2LGFSE8f6zz9teDE+0XVRO+3Vj6kaY2RFi0UtXcIHV8ny
Dq3dihm3nTcliOS5rrFkOqaJlMKbA2Pm/uBr31S3kXbCF5+k5Mjlw4d/w46AiKaDJvjY3p
y4SlGvly4Wp87oFuM0xEdsW1KqpDL/JAGJHWkDEDGUnT0MaHQFPw9fauz4BOwkO5WB9F1P
w+2/w37TAA4Fp/rHMyo1a5kCelF2xTA4WAgzVtRQCGAa6SLkMgTp2HgJqJpUB3gEVeK4qS
yOBay9qPH984dZ72eV3kVfG6HVIEl7Ppc62FFYiyz1YudhDMU1sey0bnRfX3xSSp6oLYGO
ulcy9tVbiT8fM7EnqzLnD4icCDx8MjMc1ShipzGyQIqtzWkzB7mzM3YdClS0txZ/9RAAAA
wEPDuRD6z5fzPo9lziKv4R4Rpdhbrgv+nHlgmjXDhoM4JKj4UUtrYqi8nn574T2vuu0fSY
FW2iy1M/6/QfP37ycKr3NQUsZMzQxe8LzI1h/zkGWQDlR9xooSz3s0K/0Qrdkt7+Nz3rAU
ExEAfUinkhPITMJSNkV36/Ci4pBNFFLo8QpcbiwPjwkWM3DAklZmwqGRGR1ExgJ8QkQCSP
KrYiXTQgVtEeLKiRyKqcaBxo3KW2mlZSP2qf2h+dA9VRpeMAAAAMEA1kvVQ16CCqaSWs+Q
HgdJIshwiNiY6cglrmkbdqG39NQI4EbKXVq+YJ3tIXMEF2BaFRTYW9S2Nq8lPD7HDyrm5Z
1K/eiWEYxMrgxIdAnO1b8Kwab2z3wuvgOlwAC0VMj2T+ci6ahyKhKKHgeqMjwDGevVlVun
Hu+5tUKWBpJktwf5KEEOVY03j+aQiaG8KHVHZ336pkvHqiU4V4npYUZzBSHYtXuQ0/zJar
WhUPD3544mENMiIkqopgzRS5R/nQ6ZAAAAwQDHbKn4C3MRogUftKyQWkZzHeMHSSn+Wyne
b3hTunH30Prty9hPMYU8h3jC1fLWSvQHNoLM2QIX2S/88h+MYbs4VfOgvoqSOGCb/dhTor
ZyZSI0uQ/ZpzSkuWhBH6vI/xNAfxc5bTpU3/sMJTABaLq5k1NtwzG1oNTELueEMee+/ELT
RNO/Ojv4jV9xB/e9OvUHkUcYEa28KWcbJzk8ugTV7k+2akHmHKNHA26QVxV9haq91q7dD2
ZncBAtIXihpicAAAARcm9vdEBjMDU3YmM2OTE5NjYBAg==
-----END OPENSSH PRIVATE KEY-----
"""

[passwords]
ai21 = "StateOfTheArt"
ai22 = "ArtOfTheState"
sortd = "QuestionMark?"
long_form = "long"
chat = "bot"
rv = "rv"
import_ai21_package = "import"
easy = "way"
classification = "stayclassy"
writelabel = "label"
writelabel_product = "label"
chatbot_demo = "chat"
shoe = "lala"
aws = "amazon"
h10 = "keywords"
decathlon = "ai21"
product = "ai21"
keywords = "ai21"
media_publishers = "ai21"

[api-keys]
ai21-team-prod = "iNr7n8lAvMgacJFt7dUBOOERsEYoVXhh"
ai21-algo-team-prod = "ehftPQwyxKAAUaXg6xCCDK8MmpjudeLf"
ai21-algo-team-stg = "Korw8XR2eylfEL7xOjPJ2rICkRu7OPRR"
writelabel = "W2oTKiReZYmUeYyPzkRFwDm1Loj2zkCJ"